# Generated by Django 3.0.6 on 2021-03-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20210304_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
