# Generated by Django 3.1.6 on 2021-03-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_venta_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='fecha_registro',
        ),
    ]
