# Generated by Django 3.1.6 on 2021-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20210310_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_cancelado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_terminado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
