# Generated by Django 3.1.6 on 2021-03-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20210310_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='motivo_cancelado',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
