# Generated by Django 3.1.6 on 2021-03-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_venta_motivo_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estatus',
            field=models.CharField(choices=[('1', 'Registrada'), ('2', 'Terminada'), ('3', 'Cancelada')], default=1, max_length=2),
        ),
    ]
