# Generated by Django 3.1.6 on 2021-03-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20210311_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
