# Generated by Django 3.1.6 on 2021-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_producto_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
